#pragma once

#ifdef __APPLE__
#include <Carbon/Carbon.h>
#elif defined _WIN32
#include <WinUser.h>
#elif defined __linux__
#include <X11/keysymdef.h>
#endif

#include <string>
#include <map>

namespace moduru::sys
{

class KeyCodes
{
public:
    static inline std::map<int, std::string> keyCodeNames = {
        
#ifdef __APPLE__
        { kVK_F1, "F1"  },
        { kVK_F2, "F2"  },
        { kVK_F3, "F3"  },
        { kVK_F4, "F4"  },
        { kVK_F5 , "F5"  },
        { kVK_F6 , "F6"  },
        { kVK_F7 , "F7"  },
        { kVK_F8, "F8"  },
        { kVK_F9, "F9"  },
        { kVK_F10, "F10" },
        { kVK_F11, "F11" },
        { kVK_F12, "F12" },
        
        { kVK_Escape, "esc" },
        { kVK_ANSI_Grave, "` (backtick)" },
        { kVK_ISO_Section, "§ (section mark)" },
        { kVK_Tab, "tab" },
        { kVK_CapsLock, "caps lock" },
        { kVK_Shift, "left shift" },
        { kVK_Function, "fn" },
        { kVK_Control, "left control" },
        { kVK_Option, "left option/alt" },
        { kVK_Command, "command" },
        { kVK_ANSI_Minus, "minus" },
        { kVK_ANSI_Equal, "equals" },
        { kVK_Delete, "delete" },
        { kVK_ANSI_LeftBracket, "{ (left bracket)" },
        { kVK_ANSI_RightBracket, "} (right bracket)" },
        { kVK_ANSI_Backslash, "\\ (backslash)" },
        { kVK_ANSI_Semicolon, "; (semicolon)" },
        { kVK_ANSI_Quote, "' (quote)" },
        { kVK_Return, "return" },
        { kVK_ANSI_Comma, ", (comma)" },
        { kVK_ANSI_Period, ". (period)" },
        { kVK_ANSI_Slash, "/ (slash)" },
        { kVK_RightShift, "right shift" },
        { kVK_RightOption, "right option/alt" },
        { kVK_Space, "space" },
        
        { kVK_ANSI_Keypad0, "Keypad 0" },
        { kVK_ANSI_Keypad1, "Keypad 1" },
        { kVK_ANSI_Keypad2, "Keypad 2" },
        { kVK_ANSI_Keypad3, "Keypad 3" },
        { kVK_ANSI_Keypad4, "Keypad 4" },
        { kVK_ANSI_Keypad5, "Keypad 5" },
        { kVK_ANSI_Keypad6, "Keypad 6" },
        { kVK_ANSI_Keypad7, "Keypad 7" },
        { kVK_ANSI_Keypad8, "Keypad 8" },
        { kVK_ANSI_Keypad9, "Keypad 9" },
        
        { kVK_ANSI_0, "0" },
        { kVK_ANSI_1, "1" },
        { kVK_ANSI_2, "2" },
        { kVK_ANSI_3, "3" },
        { kVK_ANSI_4, "4" },
        { kVK_ANSI_5, "5" },
        { kVK_ANSI_6, "6" },
        { kVK_ANSI_7, "7" },
        { kVK_ANSI_8, "8" },
        { kVK_ANSI_8, "9" },
        
        { kVK_ANSI_Q, "q" },
        { kVK_ANSI_W, "w" },
        { kVK_ANSI_E, "e" },
        { kVK_ANSI_R, "r" },
        { kVK_ANSI_T, "t" },
        { kVK_ANSI_Y, "y" },
        { kVK_ANSI_U, "u" },
        { kVK_ANSI_I, "i" },
        { kVK_ANSI_O, "o" },
        { kVK_ANSI_P, "p" },
        { kVK_ANSI_A, "a" },
        { kVK_ANSI_S, "s" },
        { kVK_ANSI_D, "d" },
        { kVK_ANSI_F, "f" },
        { kVK_ANSI_G, "g" },
        { kVK_ANSI_H, "h" },
        { kVK_ANSI_J, "j" },
        { kVK_ANSI_K, "k" },
        { kVK_ANSI_L, "l (letter L)" },
        { kVK_ANSI_Z, "z" },
        { kVK_ANSI_X, "x" },
        { kVK_ANSI_C, "c" },
        { kVK_ANSI_V, "v" },
        { kVK_ANSI_B, "b" },
        { kVK_ANSI_N, "n" },
        { kVK_ANSI_M, "m" },
        
        { kVK_LeftArrow, "cursor left"  },
        { kVK_RightArrow, "cursor right" },
        { kVK_UpArrow, "cursor up"    },
        { kVK_DownArrow, "cursor down"  },
        
        { kVK_ANSI_KeypadDecimal, "keypad decimal" },
        { kVK_ANSI_KeypadMultiply, "keypad multiply" },
        { kVK_ANSI_KeypadPlus, "keypad plus" },
        { kVK_ANSI_KeypadClear, "keypad clear" },
        { kVK_ANSI_KeypadDivide, "keypad divide" },
        { kVK_ANSI_KeypadEnter, "keypad enter" },
        { kVK_ANSI_KeypadMinus, "keypad minus" },
        { kVK_ANSI_KeypadEquals, "keypad equals" },
        
        { kVK_Home, "home" },
        { kVK_PageUp, "page up" },
        { kVK_End, "end" },
        { kVK_PageDown, "page down" }
        
#elif defined _WIN32

        { VK_F1, "F1"  },
        { VK_F2, "F2"  },
        { VK_F3, "F3"  },
        { VK_F4, "F4"  },
        { VK_F5, "F5"  },
        { VK_F6 , "F6"  },
        { VK_F7, "F7"  },
        { VK_F8, "F8"  },
        { VK_F9, "F9"  },
        { VK_F10, "F10" },
        { VK_F11, "F11" },
        { VK_F12, "F12" },
        
        { VK_ESCAPE, "esc" },
        { VK_TAB, "tab" },
        { VK_CAPITAL, "caps lock" },
        { VK_LSHIFT, "left shift" },
        { VK_LCONTROL, "left control" },
        { VK_LMENU, "left alt" },
        { VK_OEM_MINUS, "minus" },
        { VK_OEM_PLUS, "equals" },
        { VK_INSERT, "insert" },
        { VK_DELETE, "delete" },
        { VK_RETURN, "return" },
        { VK_OEM_COMMA, ", (comma)" },
        { VK_OEM_PERIOD, ". (period)" },
        { VK_SPACE, "space" },

        { VK_OEM_1, "; (semicolon)" },
        { VK_OEM_2, "/ (slash)" },
        { VK_OEM_3, "` (backtick)" },
        { VK_OEM_4, "{ (left bracket)" },
        { VK_OEM_6, "} (right bracket)" },
        { VK_OEM_5, "\\ (backslash)" },
        { VK_OEM_7, "' (quote)" },

        { VK_NUMPAD0, "Keypad 0" },
        { VK_NUMPAD1, "Keypad 1" },
        { VK_NUMPAD2, "Keypad 2" },
        { VK_NUMPAD3, "Keypad 3" },
        { VK_NUMPAD4, "Keypad 4" },
        { VK_NUMPAD5, "Keypad 5" },
        { VK_NUMPAD6, "Keypad 6" },
        { VK_NUMPAD7, "Keypad 7" },
        { VK_NUMPAD8, "Keypad 8" },
        { VK_NUMPAD9, "Keypad 9" },
        
        { '0', "0" },
        { '1', "1" },
        { '2', "2" },
        { '3', "3" },
        { '4', "4" },
        { '5', "5" },
        { '6', "6" },
        { '7', "7" },
        { '8', "8" },
        { '9', "9" },
        
        { 'A', "a" },
        { 'B', "b" },
        { 'C', "c" },
        { 'D', "d" },
        { 'E', "e" },
        { 'F', "f" },
        { 'G', "g" },
        { 'H', "h" },
        { 'I', "i" },
        { 'J', "j" },
        { 'K', "k" },
        { 'L', "l (letter L)" },
        { 'M', "m" },
        { 'N', "n" },
        { 'O', "o" },
        { 'P', "p" },
        { 'Q', "q" },
        { 'R', "r" },
        { 'S', "s" },
        { 'T', "t" },
        { 'U', "u" },
        { 'V', "v" },
        { 'W', "w" },
        { 'X', "x" },
        { 'Y', "y" },
        { 'Z', "z" },
        
        { VK_LEFT, "cursor left"  },
        { VK_RIGHT, "cursor right" },
        { VK_UP, "cursor up"    },
        { VK_DOWN, "cursor down"  },
        
        { VK_DECIMAL, "keypad decimal" },
        { VK_MULTIPLY, "keypad multiply" },
        { VK_ADD, "keypad plus" },
        { VK_CLEAR, "keypad clear" },
        { VK_DIVIDE, "keypad divide" },
        { VK_SUBTRACT, "keypad minus" },
        
        { VK_HOME, "home" },
        { VK_PRIOR, "page up" },
        { VK_END, "end" },
        { VK_NEXT, "page down" }
        
#elif defined __linux__

        { XK_F1, "F1"  },
        { XK_F2, "F2"  },
        { XK_F3, "F3"  },
        { XK_F4, "F4"  },
        { XK_F5, "F5"  },
        { XK_F6, "F6" },
        { XK_F7, "F7"  },
        { XK_F8, "F8"  },
        { XK_F9, "F9"  },
        { XK_F10, "F10" },
        { XK_F11, "F11" },
        { XK_F12, "F12" },
        
        { XK_Escape, "esc" },
        { XK_Tab, "tab" },
        { XK_Caps_Lock, "caps lock" },
        { XK_Shift_L, "left shift" },
        { XK_Control_L, "left control" },
        { XK_Alt_L, "left alt" },
        { XK_minus, "minus" },
        { XK_equal, "equals" },
        { XK_Insert, "insert" },
        { XK_Delete, "delete" },
        { XK_bracketleft, "{ (left bracket)" },
        { XK_bracketright, "} (right bracket)" },
        { XK_backslash, "\\ (backslash)" },
        { XK_semicolon, "; (semicolon)" },
        { XK_apostrophe, "' (quote)" },
        { XK_Return, "return" },
        { XK_comma, ", (comma)" },
        { XK_period, ". (period)" },
        { XK_slash, "/ (slash)" },
        { XK_space, "space" },
        
        { XK_0, "0" },
        { XK_1, "1" },
        { XK_2, "2" },
        { XK_3, "3" },
        { XK_4, "4" },
        { XK_5, "5" },
        { XK_6, "6" },
        { XK_7, "7" },
        { XK_8, "8" },
        { XK_9, "9" },
        
        { XK_a, "a" },
        { XK_b, "b" },
        { XK_c, "c" },
        { XK_d, "d" },
        { XK_e, "e" },
        { XK_f, "f" },
        { XK_g, "g" },
        { XK_h, "h" },
        { XK_i, "i" },
        { XK_j, "j" },
        { XK_k, "k" },
        { XK_l, "l (letter L)" },
        { XK_m, "m" },
        { XK_n, "n" },
        { XK_o, "o" },
        { XK_p, "p" },
        { XK_q, "q" },
        { XK_r, "r" },
        { XK_s, "s" },
        { XK_t, "t" },
        { XK_u, "u" },
        { XK_v, "v" },
        { XK_w, "w" },
        { XK_x, "x" },
        { XK_y, "y" },
        { XK_z, "z" },
        
        { XK_Left, "cursor left"  },
        { XK_Right, "cursor right" },
        { XK_Up, "cursor up"    },
        { XK_Down, "cursor down"  },
        
        { XK_Home, "home" },
        { XK_Page_Up, "page up" },
        { XK_End, "end" },
        { XK_Page_Down, "page down" }
#endif
        
    };
    
};
}
